// DO NOT EDIT - generated by github.com/edwarnicke/imports-gen
package imports

import (
	_ "fmt"
	_ "github.com/pkg/errors"
	_ "github.com/stretchr/testify/assert"
	_ "github.com/stretchr/testify/require"
	_ "io/ioutil"
	_ "net"
	_ "os"
	_ "path/filepath"
	_ "runtime"
	_ "syscall"
	_ "testing"
)
